config/routes.rb
ManualBlog::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => "devise/sessions", :registrations => "devise/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
       
  root :to => 'posts#index'

  resources :posts do 
  end

  match "comments/form" => "comments#create", :as=>:new_comment
  match "destroy" => "comments#destroy", :as => :destroy_comment,:method=>:delete

  match "tags/form" => "tags#create", :as=>:new_tag
  match "destroy" => "comments#destroy", :as => :destroy_tag

  get '/auth/:provider/callback', to: 'users#create_fb_account'
  match 'auth/failure', to: redirect('/')

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content
  belongs_to :post
  validates_presence_of :content
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :facebook_authorization, :only => [:create]
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment])
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        current_user.add_role :user, @comment
        format.json{render :json => {:content=>@comment.content, :user=>User.find(@comment.user_id).email, :id=>@comment.id, :post_id=>@post.id } }
      else
        format.html { redirect_to post_path(@post) }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(params[:post_id]) }
      format.json { head :no_content }
    end
  end

  def facebook_authorization
    if current_user.present?
      if current_user.provider.nil?
        binding.pry
        redirect_to user_omniauth_authorize_path(:facebook), :notice => "You need to logged in through Facebook to comment"
      end
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@post, @comment], :remote=>true, :url=>new_comment_path(:post_id=>@post)) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions span7">
    Add Comment:<br/>
    <%= f.text_field :content, :class=>"span12", :required=>true, :id=>"comment" %><br/>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>