config/routes.rb
ManualBlog::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => "devise/sessions", :registrations => "devise/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
       
  root :to => 'posts#index'

  resources :posts do 
  end

  match "comments/form" => "comments#create", :as=>:new_comment
  match "destroy" => "comments#destroy", :as => :destroy_comment,:method=>:delete

  match "tags/form" => "tags#create", :as=>:new_tag
  match "destroy" => "comments#destroy", :as => :destroy_tag

  get '/auth/:provider/callback', to: 'users#create_fb_account'
  match 'auth/failure', to: redirect('/')

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
  has_many :posts ,:through => :post_tag_relations
  has_many :post_tag_relations
  validates :name, :uniqueness => true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  def show
    @tag = Tag.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  def new
    @tag = Tag.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def create
    @post = Post.find(params[:post_id])
    @post.tags += [Tag.find_or_create_by_name(params[:tag])]
    respond_to do |format|
      if @post.save
        format.json{render :json => {:content=>@post.tags.last.name } }
      else
        format.html { redirect_to post_path(@post) }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @tag = Tag.find(params[:id])
    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for([@post, @tag], :remote=>true, :url=>new_tag_path(:post_id=>@post)) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions span7">
    Add Tag:<br/>
    <%= f.text_field :name, :class=>"span12", :required=>true, :id=>"tag" %><br/>
  </div>

<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>