config/routes.rb
ManualBlog::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => "devise/sessions", :registrations => "devise/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}
       
  root :to => 'posts#index'

  resources :posts do 
  end

  match "comments/form" => "comments#create", :as=>:new_comment
  match "destroy" => "comments#destroy", :as => :destroy_comment,:method=>:delete

  match "tags/form" => "tags#create", :as=>:new_tag
  match "destroy" => "comments#destroy", :as => :destroy_tag

  get '/auth/:provider/callback', to: 'users#create_fb_account'
  match 'auth/failure', to: redirect('/')

end

app/models/post.rb
class Post < ActiveRecord::Base
	resourcify
  attr_accessible :title, :description
  has_many :comments, :dependent => :destroy
  has_many :tags ,:through => :post_tag_relations
  has_many :post_tag_relations
  scope :by_tag, lambda { |tag_name| joins(:tags).where("tags.name = ?", tag_name) }
	def to_param
    "#{id} #{title}".parameterize
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  def index
    if params[:tag_name].present?
      @posts = Post.by_tag(params[:tag_name])
    else
      @posts = Post.all
    end
    @tags = Tag.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = @post.comments.build
    @tag = @post.tags.build
    @tags = @post.tags
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new
    @tags = Tag.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
    @tags = Tag.all
  end

  def create
    @post = current_user.posts.build(params[:post]) 
    respond_to do |format|
      if @post.save
        current_user.add_role :moderator, @post
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    tags = params[:post][:tags].split(',')
    tags.each{|t| t.strip! }
    params[:post].delete(:tags)
    @post = current_user.posts.find(params[:id])    
    tags.each do |t|  
      @post.tags += [Tag.find_or_create_by_name(t)]
    end  
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div>
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, :class=>"span10" %>
    </div><br />    

    <div>
      <%= f.label :description, "Description" %>
      <%= f.cktext_area :description, :ckeditor => {:uiColor => "#AADC6E", :toolbar => 'MyToolbar'} %>
    </div><br />

    <!-- <div> -->
      <%#= f.label :title, "Tag" %>
      <%#= select_tag :tags,options_from_collection_for_select(@tags,:id,:name,@tags.map{|u|u.id.to_s}),:class=>"chosen-select",:multiple=>true,"data-placeholder"=>"Add Admins" %>
      <%#= f.text_field :tags, :class=>"span10", :placeholder=>"Add tags" %>
    <!-- </div><br />  -->
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h2>Recent posts</h2>
<%= link_to 'Create New Post', new_post_path, :class=>"pull-right" %>

<table>
  <% @posts.each do |post| %>
    <tr><h4><%= link_to post.title.camelize, post_path(post.id) %></h4></tr>
    <tr><%= simple_format(truncate(post.description, :length => 400)) %></tr>
    <tr>
      <% if current_user.has_role? :admin or current_user.has_role? :moderator, post %>
        <%= link_to 'Edit', edit_post_path(post) %>&nbsp;|&nbsp;
        <%= link_to 'Destroy', post_path(post.id), method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;|&nbsp;
      <% end if current_user.present? %>
      <span style="color: #666;">Total&nbsp;<%= post.comments.count %>&nbsp;comments.</span>
      <%= link_to "Show More ->", post_path(post.id), :class=>"pull-right" %>
    </tr>
    <hr/>
  <% end %>
</table>
<% content_for :sidebar do %>
  <h3>Tags</h3>
  <ul class="inline">
    <% @tags.each do |tag| %>
      <%= link_to tag.name, posts_path(:tag_name=>tag.name)  %>
    <% end %>
  </ul> 
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1><br /> 

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->
	<h3><%= @post.title.camelize %></h3>	
	<%= simple_format(@post.description) %><br/>	
  <% if current_user && @post.user_id == current_user.id %>
		<%= link_to 'Edit', edit_post_path(@post) %> |
		<%= link_to 'Back', posts_path %>
	<% end %>
<h4>Comments:</h4>
<div class="comment_listing">
	<% @comments.each do |comment| %>
		<% if comment.id.present? %>
			<p><b><%= comment.user_id.present? ? User.find(comment.user_id).email : "Unknown"  %> says:</b>
				<% if current_user.has_role? :admin or current_user.has_role? :user, comment %>
					<%= link_to "X", destroy_comment_path(:id=>comment.id, :post_id=>@post.id), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"pull-right danger" %><br/>
	      <% end if current_user.present? %></p>
			<%= comment.content %><br/><br/>
			<hr/>			
		<% end %>
	<% end %>
</div>
<%= render "comments/form" %>
<% content_for :sidebar do %>
  <h4>Tags in this blog</h4>
  <ul class="inline tag_listing">
    <% @tags.each do |tag| %>
      <%= link_to tag.name, posts_path(:tag_name=>tag.name) if tag.id.present?  %>
    <% end %>
  </ul>   
	<%= render "tags/form" %>
<% end %>